<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>uninstall</AssemblyName>
    <RootNamespace>RBXDowngrader.Uninstaller</RootNamespace>
    <ApplicationIcon>app.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="app-icon.png" />
  </ItemGroup>
</Project>
